#!/bin/bash
# See: https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
# Note: you can't refactor this out: its at the top of every script so the scripts can find their includes.
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
cd "${SCRIPT_DIR}" || exit 1  # This is an unlikely failure, so don't worry too much.

source include.sh
source activate

declare -a pyfiles
for fname in "$@"; do
  case "$fname" in
    *.py)
      pyfiles+=( "$fname" )
      ;;
    *.pyi)
      pyfiles+=( "$fname" )
      ;;
    *)
      ;;
  esac
done

if [ -z "$1" ]; then
  _package_dirs=()
  while read -r package_dir; do
    _package_dirs+=( "${package_dir#./}" )
  done < <(find -maxdepth 2 -name '__init__.py' -printf '%h\n')
  exec refurb "${_package_dirs[@]}"
else
  exec refurb "${pyfiles[@]}"
fi
